### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by BT5U** [epidemics-scepticism/rcli#1]
can you compose a brief step-by-step install/usage guide? maybe some screenshots? im not sure how to use go. $(go run cli.go) didn't seem to work. this is ricochet run in terminal, correct?

**Comment by epidemics-scepticism** [comment]
Sorry, it's in a half-built state. The issue on the front page shows it. It can currently receive but not send messages, I (or someone) needs to write a patch for Yawning's ricochet implementation but if you edit the `"./ricochet"` import in config.go and tty.go to be `"github.com/Yawning/ricochet"` it should build, I was using a local copy to try and patch it up but I've never got back to it.

**Comment by epidemics-scepticism** [comment]
I've set it to use yawning's upstream lib (which is really where all the heavy lifting is done) again instead of a local copy I was using to try and patch it up. This project kinda fell by the wayside :P you might have better luck building your own based on [yawning's lib](https://github.com/yawning/ricochet) yourself. I've only done the easy part of hooking up to their lib.

``` bash
~$ export GOPATH=`mktemp -d`
~$ go get -u github.com/epidemics-scepticism/rcli
~$ file $GOPATH/bin/rcli
/tmp/tmp.hpmLcc2u88/bin/rcli: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
```
